name: GungennsGenerators
version: '1.0-SNAPSHOT'
main: com.gungenns.Main
api-version: 1.19
commands:
  generator:
    description: Main generator creation command
  reloadGenerators:
    description: reload this plugin